# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e816cc205d02365339fbdfd3d45b57d15faa8ba26acff01520ff1f30cc55758fd82f22aff0dcd30b75b2dcb4057154773c5ff6e8fb58e8b17f52a1574e5329d

test:
  secret_key_base: 53b276443fbfcb5cd978a421ccd38fb801070036487e45b89ace5cfaf87aefeec78ba67d1362d569a99bf4b91a4cf6ce0dff842596f0efe41b93aaaf46f05fd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
